name: Test Github Action
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile basic LaTeX document
        uses: ./
        with:
          root_file: Latex/main.tex
          working_directory: /
      - name: Compile LaTeX document with pre/post compile actions
        uses: ./
        with:
          root_file: test.tex
          working_directory: test/
          pre_compile: |
            rm test.pdf
          post_compile: |
            ls test.pdf
      - name: Compile multiple LaTeX documents
        uses: ./
        with:
          root_file: |
            file1.tex
            file2.tex
          working_directory: test/
      - name: Compile multiple LaTeX documents using glob
        uses: ./
        with:
          root_file: "glob_test*.tex"
          glob_root_file: true
          working_directory: test/
      - name: Compile multiple LaTeX documents in different directories
        uses: ./
        with:
          root_file: "subdir*/main.tex"
          glob_root_file: true
          working_directory: test/
          work_in_root_file_dir: true
      - name: Compile multiple LaTeX documents in different directories using extended glob
        uses: ./
        with:
          root_file: "extglob/!(subdir3)_glob/*.tex"
          glob_root_file: true
          working_directory: test/
          work_in_root_file_dir: true
      - name: Compile multiple LaTeX documents in different directories using glob star
        uses: ./
        with:
          root_file: "globstar/**/*.tex"
          glob_root_file: true
          working_directory: test/
          work_in_root_file_dir: true
      - name: Compile LaTeX document with math symbols
        uses: ./
        with:
          root_file: math.tex
          working_directory: test/
      - name: Compile LaTeX document with biblatex/biber
        uses: ./
        with:
          root_file: biblatex.tex
          working_directory: test/
      - name: Compile LaTeX document with eps figure
        uses: ./
        with:
          root_file: eps.tex
          working_directory: test/
      - name: Compile LaTeX document with minted and lualatex
        uses: ./
        with:
          root_file: minted.tex
          working_directory: test/
          latexmk_shell_escape: true
          latexmk_use_lualatex: true
      - name: Download extra fonts
        run: |
          curl -OL https://github.com/google/fonts/raw/main/ofl/notosans/NotoSans-Regular.ttf
      - name: Compile LaTeX document with extra_fonts
        uses: ./
        with:
          root_file: extra_fonts.tex
          working_directory: test/
          latexmk_use_xelatex: true
          extra_fonts: "./../NotoSans-Regular.ttf"
      - name: Compile LaTeX document with arara and graphviz
        uses: ./
        with:
          root_file: graphviz.tex
          working_directory: test/
          compiler: arara
          args: "--verbose"
      # https://github.com/xu-cheng/latex-action/issues/16
      - name: Test Action with Github Default Template
        uses: ./
        with:
          # The root LaTeX file to be compiled
          root_file: Latex/main.tex
      - name: Check pdf files
        run: |
          file Latex/LaTeX_compiled.pdf | grep -q ' PDF '
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: test
        if: always()
